import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AdminProvider } from "@/contexts/AdminContext";
import AdminLoginModal from "@/components/AdminLoginModal";
import AdminButton from "@/components/AdminButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminProvider>
          <nav className="bg-gray-100 p-4">
            <div className="max-w-7xl mx-auto flex justify-between items-center">
              <div className="flex space-x-4">
                <Link href="/" className="text-blue-600 hover:underline">
                  Home
                </Link>
                <Link href="/about" className="text-blue-600 hover:underline">
                  About
                </Link>
                <Link href="/work" className="text-blue-600 hover:underline">
                  Work
                </Link>
                <Link href="/archive" className="text-blue-600 hover:underline">
                  Archive
                </Link>
              </div>
            </div>
          </nav>
          {children}
          <AdminButton />
          <AdminLoginModal />
        </AdminProvider>
      </body>
    </html>
  );
}
